# Generated by Django 4.2.4 on 2023-08-23 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopino', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='ShopAddress',
            new_name='shop_address',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='ShopDescription',
            new_name='shop_description',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='ShopName',
            new_name='shop_name',
        ),
    ]
