# Generated by Django 4.2.4 on 2023-08-26 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopino', '0003_shop_shop_followers_alter_shop_shop_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='shop_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='shop_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='shop_followers',
            new_name='followers',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='shop_name',
            new_name='name',
        ),
    ]
