# Generated by Django 4.2.4 on 2023-08-27 10:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopino', '0005_alter_shop_address_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bookmarked_by',
            field=models.ManyToManyField(related_name='bookmarked_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
