# Generated by Django 4.2.4 on 2023-08-30 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopino', '0007_userbookmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bookmarked_by',
        ),
    ]
